### ISSUE TITLE
Feedback for first submission

### ISSUE THREAD

**Issue by Anisha7** [AwesomeZaidi/Data-Structures#1]
Good Job on completing your first submission. Here's what you can do to improve:
- I cannot find your code for the base conversion challenges. (Did you push it to GitHub?)
- Your palindrome’s iterative implementation does not pass tests. Debug your code! Use comments.
- Refactoring your strings code is required! Look for code that is common between your three functions and try to divide it up in helper functions OR call one of the functions in the other two, such that there is no duplicate code in your file.
- Good job on implementing a doubly linked list. Unfortunately, the linked list implementations currently fail most unit tests. Try to print out what your code is doing/where it is failing to debug your code.

**Comment by AwesomeZaidi** [comment]
Thanks for the feedback Anisha!

- Ah my apologies I had my bases in the old repo, but it has been now been pushed and passing all tests.
- For the Palindrome, yikes I forgot to check for special letter cases in my iterative! Fixed! I have a strong use of comments.
- I just refactored my strings code to have a cool helper function that works with all the functions so i reduced duplicate code, feels great 😁
- Whoops for Linked Lists I forgot to increment size in some places, fixed.

**Comment by Anisha7** [comment]
Yay, good job on implementing those! A couple more suggestions for good coding practices:
-  Annotate your code for space and time complexities (Alan had this as a base challenge for Strings)
- Try to add more unit tests for strings implementation for more thorough testing
- Implement unit tests for doubly linked list. Use Alan's given unit tests for linked lists as a reference. Its good practice to write tests for your code!

I apologize for not including this in the above message. However, the above suggestions are not required.
