### ISSUE TITLE
Feedback on second submission

### ISSUE THREAD

**Issue by Anisha7** [AwesomeZaidi/Data-Structures#2]
Good job on completing the second coding challenge! Here's some feedback to improve:

- Your ArrayQueue does not pass tests. The bug lies in your front() function. is_empty is not a property. It is a method. You must call it like this —> `self.is_empty( )` in order for it to be used. In addition, think about how your is_empty function is working right now. Currently, it checks to see if ‘self.list’ (the property that stores your linked list in this queue class) is None. This results in a boolean True or False value. There is a bug in the is_empty function as well. Do you reset and reinitialize your linked list every time it is empty? Is self.list really equal None? Is it really set to None?
- You are missing your implementation for issubset in Sets. This is a required challenge. You also need to implement your size property to track the size. Currently, it is always 0.
- Your medium post needs to be 800-1000 words. You are so close!!

**Comment by AwesomeZaidi** [comment]
Hi Anisha,

Thanks for the phenomenal feedback as always!

✅ - Ah thanks for the insight! I fixed my ArrayQueue to not check if its empty but to see if its length is 0 and now I'm passing all test cases.
✅ - I added the issubset function to Set class and track size now as well.
✅ - I increased my medium article length to be 825.

**Comment by Anisha7** [comment]
Sorry about not adding this in earlier. Implementing tests is required for each method in your set class (including size and issubset), and your add function should deal with duplicates --> sets cannot have duplicates. Please fix these two issues, and you'll be on track :)

**Comment by AwesomeZaidi** [comment]
I've gone ahead and fixed these!

- For the add function, I do believe since I'm going self.map.add(element) within that function under the hood in my hash table class it does the work to make sure the element is unique otherwise it isn't added but i've gone ahead and added another check in the add function to be sure, I could be wrong though I'm not too sure!
