### ISSUE TITLE
Feedback: Number Bases & Search Algorithms

### ISSUE THREAD

**Issue by anselb** [AwesomeZaidi/Data-Structures#4]
- Nice work on you number bases. I would've liked to seen some comments that explain what some of the lines of code were doing as if I had wasn't familiar with number base conversion (line 31 or the whole while loop starting on line 55). 
- Your recursive binary search is good as well, but there are some bugs in your iterative binary search. One thing I noticed was that your `mid` calculation on line 45 was off. I also noticed that you annotated the `len()` function as O(n), but it is [actually O(1)](https://stackoverflow.com/questions/1115313/cost-of-len-function).

**Comment by AwesomeZaidi** [comment]
Thanks @anselb I went ahead and fixed the iterative algorithm.
