### ISSUE TITLE
Feedback on Palindrome and String Searching Algorithms

### ISSUE THREAD

**Issue by fchikwekwe** [AwesomeZaidi/Data-Structures#5]
Good work on getting through this first assignment. 

On your string searching algorithm, you could have added more than 3 tests to make sure that your algorithm is robust. Additionally, there are a few place where you could have refactored your code to be easier to read. Lines 14 - 17 of your `strings.py` could be changed to be more terse and Pythonic and line 9 could have used some comments to clarify what you're doing there. 

I noticed that generally you rely on semantic variable naming to make your code readable, but you don't write enough comments. writing more comments would do a lot to make your code easier to read.

**Comment by AwesomeZaidi** [comment]
Thanks for the feedback!

Also, good catch on line 9, a comment there will be great.
