### ISSUE TITLE
Feedback: Trees & Tree Traversals

### ISSUE THREAD

**Issue by anselb** [AwesomeZaidi/Data-Structures#8]
- Your binary tree runs well for the most part, but your post order traversal needs a couple bug fixes. Your method is only four lines, so it should be a couple easy fixes if you look closely. First, what method are your calling recursively? Second, what is getting visited? If you can't figure out the second one, look at your other traversals.

**Comment by AwesomeZaidi** [comment]
Thanks for the feedback! Ah, silly mistakes! I had to call the right function and visit node.data!
